// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.2.0
// - protoc             v4.25.3
// source: notification.proto

package notification_v1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// NotificationV1Client is the client API for NotificationV1 service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type NotificationV1Client interface {
	CreateMessage(ctx context.Context, in *CreateMessageRequest, opts ...grpc.CallOption) (*CreateMessageResponse, error)
}

type notificationV1Client struct {
	cc grpc.ClientConnInterface
}

func NewNotificationV1Client(cc grpc.ClientConnInterface) NotificationV1Client {
	return &notificationV1Client{cc}
}

func (c *notificationV1Client) CreateMessage(ctx context.Context, in *CreateMessageRequest, opts ...grpc.CallOption) (*CreateMessageResponse, error) {
	out := new(CreateMessageResponse)
	err := c.cc.Invoke(ctx, "/notification_v1.NotificationV1/CreateMessage", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// NotificationV1Server is the server API for NotificationV1 service.
// All implementations must embed UnimplementedNotificationV1Server
// for forward compatibility
type NotificationV1Server interface {
	CreateMessage(context.Context, *CreateMessageRequest) (*CreateMessageResponse, error)
	mustEmbedUnimplementedNotificationV1Server()
}

// UnimplementedNotificationV1Server must be embedded to have forward compatible implementations.
type UnimplementedNotificationV1Server struct {
}

func (UnimplementedNotificationV1Server) CreateMessage(context.Context, *CreateMessageRequest) (*CreateMessageResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateMessage not implemented")
}
func (UnimplementedNotificationV1Server) mustEmbedUnimplementedNotificationV1Server() {}

// UnsafeNotificationV1Server may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to NotificationV1Server will
// result in compilation errors.
type UnsafeNotificationV1Server interface {
	mustEmbedUnimplementedNotificationV1Server()
}

func RegisterNotificationV1Server(s grpc.ServiceRegistrar, srv NotificationV1Server) {
	s.RegisterService(&NotificationV1_ServiceDesc, srv)
}

func _NotificationV1_CreateMessage_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateMessageRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NotificationV1Server).CreateMessage(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/notification_v1.NotificationV1/CreateMessage",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NotificationV1Server).CreateMessage(ctx, req.(*CreateMessageRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// NotificationV1_ServiceDesc is the grpc.ServiceDesc for NotificationV1 service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var NotificationV1_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "notification_v1.NotificationV1",
	HandlerType: (*NotificationV1Server)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreateMessage",
			Handler:    _NotificationV1_CreateMessage_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "notification.proto",
}
